# vim: set ft=zsh et :
#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ -z "$BROWSER" && "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
else
  export BROWSER='google-chrome-stable'
fi

[[ -f "${HOME}/.env" ]] && . "${HOME}/.env"

#
# Editors
#

export EDITOR='nvim'
export VISUAL='nvim'
export PAGER='less'
bindkey -v

#
# Language
#

export LANG='en_US.UTF-8'
export LC_ALL=en_US.UTF-8
export TIMEFMT=$'%J:\nreal\t%*E\nuser\t%U\nsys\t%S\n'

#
# Misc. Environment
#

# export QT_AUTO_SCREEN_SCALE_FACTOR=1
export GL_ENABLE_DEBUG_ATTACH=1
export KEYTIMEOUT=1
export GPG_TTY=$(tty)
export RUBY_CONFIGURE_OPTS="--enable-shared"
export MAKEFLAGS="-j10"
export JAVA_HOME="/usr/lib/jvm/java-25-openjdk"
export AWS_REGION="us-west-2"

# bun
export BUN_INSTALL="$HOME/.bun"
# bun completions
[ -s "${HOME}/.bun/_bun" ] && source "${HOME}/.bun/_bun"

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  $BUN_INSTALL/bin
  $HOME/.cargo/bin
  $HOME/{,s}bin(N)
  $HOME/.local/{,s}bin(N)
  $HOME/.local/share/gem/ruby/3.0.0/bin
  $HOME/go/bin
  /opt/{homebrew,local}/{,s}bin(N)
  /usr/local/{,s}bin(N)
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if [[ -z "$LESSOPEN" ]] && (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi
