# vim: set ft=zsh et :
#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ -z "$BROWSER" && "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
# else
#   export BROWSER='google-chrome-stable'
fi

[[ -s "${HOME}/.env" ]] && . "${HOME}/.env"

#
# Editors
#

export EDITOR='nvim'
export VISUAL='nvim'
export PAGER='less'
bindkey -v

#
# Language
#

export LANG='en_US.UTF-8'
export LC_ALL=en_US.UTF-8
export TIMEFMT=$'%J:\nreal\t%*E\nuser\t%U\nsys\t%S\n'

#
# Misc. Environment
#

# export QT_AUTO_SCREEN_SCALE_FACTOR=1
export GL_ENABLE_DEBUG_ATTACH=1
export KEYTIMEOUT=1
export GPG_TTY=$(tty)
export RUBY_CONFIGURE_OPTS="--enable-shared"
export MAKEFLAGS="-j10"
export AWS_REGION="us-west-2"

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# bun
if [[ -d $HOME/.bun ]]; then
  export BUN_INSTALL="$HOME/.bun"
  # bun completions
  [ -s $HOME/.bun/_bun ] && source "$HOME/.bun/_bun"
  path=($BUN_INSTALL/bin $path)
fi

# cargo/rust
if [[ -d $HOME/.cargo/bin ]]; then
  path=($HOME/.cargo/bin $path)
fi

# go
if [[ -d $HOME/go/bin ]]; then
  path=($path $HOME/go/bin)
fi


# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  $HOME/{,s}bin(N)
  $HOME/.local/{,s}bin(N)
  /opt/{homebrew,local}/{,s}bin(N)
  /usr/local/{,s}bin(N)
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if [[ -z "$LESSOPEN" ]] && (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi
