# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

setopt ALIAS_FUNC_DEF
# setopt COMPLETEALIASES
export ZSH_ENABLE_COMPFIX=true

(( $+TMUX )) && unset zle_bracketed_paste

# random aliases
alias vim='nvim' # heresy, i know
alias ivm='vim' # i do this all the time
alias vi='nvim'
alias iv='vi' # see above
alias sl='ls'
alias beg="RUBYOPT=\"-W0\" bundle exec guard"
alias nr="repl.history"
alias mux="$commands[tmuxinator]"
alias music="vimpc"

# directory aliases
alias take='mkdcd'
alias d='dirs -v | head -10'
alias md='mkdir -p'
alias rd=rmdir
alias -- -='cd -'

# tmux aliases
function ta {
  local args=$@
  if [[ $# -ge 1 ]]; then
    args="-t$args"
  fi
  tmux attach $args
}
alias ts='tmux new-session -s'
alias tl='tmux list-sessions'
alias tksv='tmux kill-server'
alias tkss='tmux kill-session -t'

alias initidf='. $HOME/esp/esp-idf/export.sh'

alias echo_err='paplay /usr/share/sounds/Oxygen-K3B-Finish-Error.ogg'
alias echo_done='paplay /usr/share/sounds/Oxygen-K3B-Finish-Success.ogg'

unsetopt PUSHD_MINUS
unsetopt AUTO_NAME_DIRS     # Don't set auto_name_dirs because it messes up prompts

# This mashes the rtags daemon
if (( $+aliases[rdm] )); then
  unalias rdm
fi

# if [[ -d "$(pyenv root 2>/dev/null)/plugins/pyenv-virtualenv" ]]; then
#   eval "$(pyenv virtualenv-init -)"
# fi

if (( $+commands[direnv] )); then
  eval "$(direnv hook zsh)"
fi

# autoload -Uz bashcompinit && bashcompinit

eval "$(_PIO_COMPLETE=zsh_source pio)"
eval "$(uv generate-shell-completion zsh)"

alias claude="${HOME}/.claude/local/claude"
