# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

setopt ALIAS_FUNC_DEF
# setopt COMPLETEALIASES
export ZSH_ENABLE_COMPFIX=true

(( $+TMUX )) && unset zle_bracketed_paste

# random aliases
alias vim='nvim' # heresy, i know
alias ivm='vim' # i do this all the time
alias iv='vi' # see above
alias beg="RUBYOPT=\"-W0\" bundle exec guard"
alias nr="repl.history"
alias mux="$commands[tmuxinator]"

# directory aliases
alias d='dirs -v | head -10'
alias md='mkdir -p'
alias rd=rmdir
alias -- -='cd -'

# pip aliases
# if (( ! $+commands[pip] )); then
#   alias pip="pip3"
# fi
alias pipup="pip freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs pip install -U"
alias pip3up="pip3 freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs pip3 install -U"

# tmux aliases
alias ta='tmux attach -t'
alias ts='tmux new-session -s'
alias tl='tmux list-sessions'
alias tksv='tmux kill-server'
alias tkss='tmux kill-session -t'

unsetopt PUSHD_MINUS
unsetopt AUTO_NAME_DIRS     # Don't set auto_name_dirs because it messes up prompts

# This mashes the rtags daemon
if (( $+aliases[rdm] )); then
  unalias rdm
fi

if (( $+commands[direnv] )); then
  eval "$(direnv hook zsh)"
fi

function take {
  mkdir -p $1
  cd $1
}

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
